from .intent_prompts import INTENT_CLASSIFICATION_SYSTEM_PROMPT
from .email_prompts import EMAIL_SUMMARIZATION_SYSTEM_PROMPT, EMAIL_REPLY_DRAFT_SYSTEM_PROMPT
from .calendar_prompts import CALENDAR_PLANNING_SYSTEM_PROMPT, DAILY_PLANNER_SYSTEM_PROMPT

__all__ = [
    "INTENT_CLASSIFICATION_SYSTEM_PROMPT",
    "EMAIL_SUMMARIZATION_SYSTEM_PROMPT",
    "EMAIL_REPLY_DRAFT_SYSTEM_PROMPT",
    "CALENDAR_PLANNING_SYSTEM_PROMPT",
    "DAILY_PLANNER_SYSTEM_PROMPT",
]
