from enum import Enum

class IntentType(str, Enum):
    READ_EMAIL = "READ_EMAIL"
    SUMMARIZE_INBOX = "SUMMARIZE_INBOX"
    DRAFT_REPLY = "DRAFT_REPLY"
    SEND_EMAIL = "SEND_EMAIL"
    CHECK_SCHEDULE = "CHECK_SCHEDULE"
    SCHEDULE_MEETING = "SCHEDULE_MEETING"
    FIND_SLOTS = "FIND_SLOTS"
    CREATE_REMINDER = "CREATE_REMINDER"
    DAILY_PLAN = "DAILY_PLAN"
    GENERAL_QUERY = "GENERAL_QUERY"
    UNKNOWN = "UNKNOWN"

class SystemLimits:
    MAX_RESPONSE_TOKENS = 512
    MAX_HISTORY_MESSAGES = 6
    MAX_EMAIL_BODY_LENGTH = 400
    MAX_EMAILS_PER_FETCH = 5
    MAX_CALENDAR_EVENTS_PER_FETCH = 10
